# Varius NumPy Methods

## Reshape Method

Used to convert the number of arrays dimensions

In [1]:
import numpy as np

In [9]:
c1 = np.array([1, 2, 3, 4, 5, 6])
c1

array([1, 2, 3, 4, 5, 6])

This array is converted to a 2-dimensional array of 2 row and 3 columns using __reshaoe__ method

In [10]:
c2 = c1.reshape((2, 3))
c2

array([[1, 2, 3],
       [4, 5, 6]])

### Ravel and flatten Method

Converts a 2-dimmensional armray to a one-dimensional array

In [14]:
c3 = c2.ravel()
c3

array([1, 2, 3, 4, 5, 6])

In [15]:
c4 = c2.flatten()
c4

array([1, 2, 3, 4, 5, 6])

## Duplication

In [16]:
a = np.array([1, 2, 3])
a1 = a

In [18]:
print(a, a1)

[1 2 3] [1 2 3]


This way, __a__ and __a1__, are in a reference relationship, and chenging the value of one, will also change the value of the other

In [19]:
a[2] = 10
a1

array([ 1,  2, 10])

### Copy

To avoid this reference relationship, we can use the copy function

In [21]:
b = np.array([1, 2, 3])
b1 = b.copy()

array([1, 2, 3])

In [22]:
b[2] = 5
b1

array([1, 2, 3])

## Random numher

the __random__ function can be used to generate a sequence of random numbers between 0 and 1 

Lets generate a two-dimensional matrix consisting of 4 row and 2 columns

In [23]:
f_array = np.random.random((4, 2))
f_array

array([[0.70282038, 0.46807367],
       [0.06024482, 0.27956517],
       [0.46702268, 0.19463635],
       [0.83159152, 0.54298532]])

In [28]:
np.random.seed(10)
np.random.randint(1, 10, (3, 5))

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9]])